### ISSUE TITLE
Database Json sample from table Error

### ISSUE THREAD

**Issue by Nasller** [maximehamm/Any2Json#4]
Json prettifier error : class com.intellij.database.dialects.mysql.model.MysqlImplModel$TableColumn cannot be cast to class com.intellij.database.dialects.postgres.model.PgLocalTableColumn (com.intellij.database.dialects.mysql.model.MysqlImplModel$TableColumn and com.intellij.database.dialects.postgres.model.PgLocalTableColumn are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @10c1d929)

IDEA 2021.1.2
VERSION 2.16.7

**Comment by maximehamm** [comment]
Thank you ! 
Fixed with new release 2.17 (available today or tomorrow)
If you enjoy my plugin, please add a review at IntelliJ market place :)

**Comment by Nasller** [comment]
OK Thanks
